apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-node-affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-node-affinity
  template:
    metadata:
      labels:
        app: nginx-node-affinity
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/e2e-az-name
                operator: In
                values:
                - e2e-az1
                - e2e-az2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-node-antiaffinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-node-antiaffinity
  template:
    metadata:
      labels:
        app: nginx-node-antiaffinity
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/e2e-az-name
                operator: NotIn
                values:
                - e2e-az1