apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod-affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod-affinity
  template:
    metadata:
      labels:
        app: nginx-pod-affinity
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx-pod-affinity
            topologyKey: kubernetes.io/hostname
