apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod-antiaffinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod-antiaffinity
  template:
    metadata:
      labels:
        app: nginx-pod-antiaffinity
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx-pod-antiaffinity
            topologyKey: kubernetes.io/hostname
