apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
data:
  SECRET_KEY: SGVsbG8sIFNlY3JldCE=  # "Hello, Secret!" in base64
  ANOTHER_SECRET: QW5vdGhlciBTZWNyZXQ=  # "Another Secret" in base64
  config.json: | 
    ewogICAgImtleSI6ICJ2YWx1ZSIsCiAgICAiYXJyYXkiOiBbCiAgICAgICIxIiwKICAgICAgIjIiCiAgICBdCn0=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-secret-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo-secret-env
  template:
    metadata:
      labels:
        app: podinfo-secret-env
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo:latest
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: example-secret
                key: SECRET_KEY
          - name: ANOTHER_SECRET
            valueFrom:
              secretKeyRef:
                name: example-secret
                key: ANOTHER_SECRET

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-secret-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo-secret-volume
  template:
    metadata:
      labels:
        app: podinfo-secret-volume
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo:latest
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
          subPath: config.json
      volumes:
      - name: secret-volume
        secret:
          secretName: example-secret
