apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3 # number of replicas 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx # This label is applied to the pod should be the same as the selector
        # You are free to add as any labels as you want but full set of selector labels must match the labels in the template
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
        - containerPort: 80