apiVersion: v1
kind: Pod
metadata:
  name: network-shared-pod
spec:
  containers:
  - name: container1
    image: nginx
  - name: container2
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]

# kubectl exec -it network-shared-pod -c container2 sh
# apk add curl
# curl localhost