# Create a persistent volume 
# This won't work in my case because my cloud provider 
# doesn't support static provisioning

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage

---
# This will work but this is pretty much useless
# because the data is on the node and not in the cloud
# and it will be lost if the node is deleted
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data
    type: DirectoryOrCreate
