apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-example-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-using-dynamic-pv
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: dynamic-example-pvc
